from .llm_openai import (
    NODE_CLASS_MAPPINGS as OPENAI_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OPENAI_DISPLAY_MAPPINGS,
)
from .llm_ollama import (
    NODE_CLASS_MAPPINGS as OLLAMA_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OLLAMA_DISPLAY_MAPPINGS,
)
from .llm_llamacpp import (
    NODE_CLASS_MAPPINGS as LLAMACPP_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LLAMACPP_DISPLAY_MAPPINGS,
)
from .text import (
    NODE_CLASS_MAPPINGS as TEXT_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_DISPLAY_MAPPINGS,
)
from .segs_caption import (
    NODE_CLASS_MAPPINGS as SEGS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEGS_DISPLAY_MAPPINGS,
)

# Merge all mappings
NODE_CLASS_MAPPINGS = {
    **OPENAI_MAPPINGS,
    **OLLAMA_MAPPINGS,
    **LLAMACPP_MAPPINGS,
    **TEXT_MAPPINGS,
    **SEGS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **OPENAI_DISPLAY_MAPPINGS,
    **OLLAMA_DISPLAY_MAPPINGS,
    **LLAMACPP_DISPLAY_MAPPINGS,
    **TEXT_DISPLAY_MAPPINGS,
    **SEGS_DISPLAY_MAPPINGS,
}

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
